### ISSUE TITLE
Make build failure

### ISSUE THREAD

**Issue by jonje** [RyliD/NUOS#1]
The build breaks after the latest commit 6c58b9cc4fd150cbaa194f0ff25de74fad46f428. Here is the output.
startfiles
obj/cstartup.o: In function `cstartup':
cstartup.c:(.text+0x80): undefined reference to`init_devices'
collect2: error: ld returned 1 exit status
make: **\* [bin/kernel7.elf] Error 1

**Comment by shallada** [comment]
Well that sucks!

**Comment by jonje** [comment]
Looks like everything builds now.

**Comment by shallada** [comment]
I’m glad to hear it
